### ISSUE TITLE
ITerminalConsole display information for other modes also

### ISSUE THREAD

**Issue by Nilavarasi-Ashika** [perpetualintelligence/oneterminal#103]
**Is your feature request related to a problem? Please describe.**
ITerminalConsole display information TerminalSystemConsole console mode, same need for other modes also like Tcp, Http etc.,

Runtime
OS: Linux
.NET 7.0.2
pi-cli v.5.1.1-rc

**Comment by Nilavarasi-Ashika** [comment]
@ameyasubhedarats @VijayakumarKothapalle @gilvargas FYI

**Comment by Nilavarasi-Ashika** [comment]
Please update the documentation for latest release.

**Comment by perpetualintelligencegit** [comment]
You can provide your custom implementation for any ITerminalConsole that is specific to your terminal front end. E.g., the Default we provide for the System.Console.

**Comment by perpetualintelligencegit** [comment]
@Nilavarasi-Ashika: Please provide elaborate information of your ask with examples if possible.

**Comment by Nilavarasi-Ashika** [comment]
TerminalSystemConsole for console mode of routing, need an ability for other modes of routing such as Tcp, Http.

**Comment by asperpint** [comment]
@Nilavarasi-Ashika: It is still not clear to us what is your ask with this issue? Specifically in terms of display information for ITerminalConsole. We are closing this issue. If you continue to face this problem, please create a new issue and add detailed explanation of your ask.
