### ISSUE TITLE
Remove hardcode UnicodeTextHandler in CommandBuilder

### ISSUE THREAD

**Issue by perpetualintelligencegit** [perpetualintelligence/oneterminal#105]
**Describe the bug**

Make this configurable in  CommandBuilder.cs

// UnicodeTextHandler is hard-coded
commandDescriptor.OptionDescriptors = new OptionDescriptors(new UnicodeTextHandler(), optionDescriptors);

**Comment by asperpint** [comment]
Starting 5.5.1 Text handler is not passed explicitly allowing consistent text handling across entire terminal.
