### ISSUE TITLE
Default --help -h causes exception

### ISSUE THREAD

**Issue by ameyasubhedarats** [perpetualintelligence/oneterminal#106]
**Describe the bug**
When using the default HelpLoggerProvider an exception is raised

`
The request failed. command_string="sibsvr -h" info="Unable to cast object of type 'System.Collections.Generic.KeyValuePair`2[System.String,PerpetualIntelligence.Terminal.Commands.OptionDescriptor]' to type 'PerpetualIntelligence.Terminal.Commands.OptionDescriptor'."
`

**Comment by ameyasubhedarats** [comment]
Another improvement, why is IHelpProvider a separate service? I should be able to execute my custom Help as a new CommandRunner !

**Comment by perpetualintelligencegit** [comment]
The issue listed is fixed in 5.3.x

IHelpProvider provides an abstraction to render help. The default implementation `HelpLoggerProvider` logs the help with standard ILogger. You can provide your custom implementation to render help.
