### ISSUE TITLE
What is the difference between IErrorPublisher and IExceptionPublisher

### ISSUE THREAD

**Issue by apspi** [perpetualintelligence/oneterminal#11]
The Cli builder has AddPublisher method that registers IErrorPublisher and IExceptionPublisher. What's the difference and when to use them ?

Use case with examples and docs will be useful.

**Comment by perpetualintelligencegit** [comment]
IErrorPublisher and IExceptionPublisher are obsolete in favor of IExceptionHandler, which handles any error scenarios in the terminal execution.
