### ISSUE TITLE
Support multiple arguments in default argument syntax

### ISSUE THREAD

**Issue by apspi** [perpetualintelligence/oneterminal#23]
**Is your feature request related to a problem? Please describe.**
At present the CLI framework supports 1 default argument, I would like to provide multiple arguments in the default argument syntax.

**Describe the solution you'd like**
Example: dotnet nuget [<PACKAGE_NAME> <PACKAGE_VERSION>]  
Here PACKAGE_NAME, PACKAGE_VERSION are specified in default argument syntax.

**Comment by perpetualintelligencegit** [comment]
Supported in 5.3.1.
