### ISSUE TITLE
How do we send command response back to client with custom routing service

### ISSUE THREAD

**Issue by ameyasubhedarats** [perpetualintelligence/oneterminal#47]
**Describe the bug**
We had to implement our custom routing service with TCP/IP and process the result to send it back to the client. The default Tcp routing service does not send the result back to the client.

**Expected behavior**
A framework capability to return the command response back to the client when using a custom routing service.

**Runtime**
 - OS: linux
 - .NET 7.0.3
 - pi-cli: 4.3.x

**Comment by asperpint** [comment]
You can use ProcessAsync on the CommandRunnerResult to implement your custom logic to send the response back to client with custom router.
