### ISSUE TITLE
ability to run third party dlls

### ISSUE THREAD

**Issue by Nilavarasi-Ashika** [perpetualintelligence/oneterminal#55]
**Is your feature request related to a problem? Please describe.**
we need ability to load assembly which contain custom command.

**Describe the solution you'd like**
For example, we are having commands like start, stop there we need an ability to add other custom commands which is there in third party dll.

**Comment by Nilavarasi-Ashika** [comment]
@ChandramouliShridharan @ameyasubhedarats @VijayakumarKothapalle FYI

**Comment by perpetualintelligencegit** [comment]
@Nilavarasi-Ashika, are you asking for the ability to discover commands from multiple DLLs or Packages that do not have static dependencies with your terminal or CLI app? E.g., dynamically loading and then discovering the commands.

**Comment by Nilavarasi-Ashika** [comment]
Yes, Need an ability to discover commands from multiple DLLs or Packages as in mentioned above.

**Comment by asperpint** [comment]
Starting 5.5.1 terminal framework now supports Integration namespace that allows to check and load third party DLLs that can contain command descriptors and runners. Currently, this is supported only for declarative syntax.
